apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: catalogue-pipeline-run
spec:
  serviceAccountName: tekton-service-account
  pipelineRef:
    name: catalogue-pipeline
  params:
  - name: image
    value: reabaln/catalogue
  - name: tag
    value: "0.1"
  - name: test-image
    value: reabaln/e2e-test
  - name: test-tag
    value: "0.3"
  - name: service
    value: catalogue
  workspaces:
  - name: shared-workspace
    persistentvolumeclaim:
      claimName: catalogue-source-pvc
