apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: backend-ci-binding-admin
  namespace: test
subjects:
  - kind: ServiceAccount
    name: tekton-service-account
    namespace: test 
roleRef:
  kind: ClusterRole
  name:  backend-ci-binding-admin
  apiGroup: rbac.authorization.k8s.io
