apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: socks-ingress
  annotations:
    ingress.kubernetes.io/ssl-redirect: "false"
spec:
  rules:
  - http:
      paths:
      - path: /
        backend:
          serviceName: front-end
          servicePort: 80
      - path: /carts
        backend:
          serviceName: carts
          servicePort: 80
      - path: /shipping
        backend:
          serviceName: shipping
          servicePort: 80
      - path: /orders
        backend:
          serviceName: orders
          servicePort: 80
      - path: /catalogue
        backend:
          serviceName: catalogue
          servicePort: 80
      - path: /users
        backend:
          serviceName: users
          servicePort: 80

