apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: e2e-test
spec:
  params:
    - name: path
      type: string
      description: Path to the manifest to apply
    - name: imageUrl
      type: string
      description: Url of image repository
    - name: imageTag
      type: string
      description: Tag of the images to be used.
      default: "latest"

  workspaces:
    - name: source
  steps:
  - name: run-test
    image: $(params.imageUrl):$(params.imageTag)
    command: ["/bin/sh"]
    args:
      - "-c"
      - "$(params.path)"
