apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: e2e-test
spec:
  params:
    - name: path
      type: string
      description: Path to the manifest to apply
    - name: service
      type: string
      description: Service under test
    - name: imageUrl
      type: string
      description: Url of image repository
    - name: imageTag
      type: string
      description: Tag of the images to be used.
      default: "latest"
  workspaces:
    - name: source

  steps:
  - name: pods-status
    image: lachlanevenson/k8s-kubectl
    command: ["kubectl"]
    args:
      - "wait"
      - "--for=condition=Ready"
      - "pods"
      - "-l"
      - "$(params.service)"
      - "timeout=600s"

  - name: run-test
    image: $(params.imageUrl):$(params.imageTag)
    script: |
      #!/bin/sh
      "$(workspaces.source.path)/$(params.path)"

