apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: e2e-test
spec:
  params:
    - name: path
      type: string
      description: Path to the manifest to apply
    - name: service
      type: string
      description: Service under test
    - name: imageUrl
      type: string
      description: Url of image repository
    - name: imageTag
      type: string
      description: Tag of the images to be used.
      default: "latest"
  workspaces:
    - name: source
  steps:
  - name: run-test
    image: $(params.imageUrl):$(params.imageTag)
    script: |
      #!/bin/sh
       while [[ $(kubectl get pods -n test -l app="$(params.service)"  -o 'jsonpath={..status.conditions[?(@.type=="Ready")].status}') != "True" ]]; \
 do echo "waiting for pod to be ready" && sleep 30; done
      "$(workspaces.source.path)/$(params.path)"

