apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: deploy-using-kubectl-production
spec:
  params:
    - name: path
      type: string
      description: Path to the manifest to apply
  workspaces:
    - name: source
  steps:
    - name: run-kubectl
      image: lachlanevenson/k8s-kubectl
      command: ["kubectl"]
      args:
        - "apply"
        - "-f"
        - "$(workspaces.source.path)/$(params.path)"
        - "-n"
        - "prod"

