apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: tekton-pipeline
spec:
  resources:
    - name: source-repo
      type: git
    - name: web-image
      type: image
  params:
    - name: image-version
      type: string
    - name: environment
      type: string
    - name: cluster-url
      type: string
      default: $(resources.local-cluster.url)
    - name: cluster-token
      type: string
      default: $(resources.local-cluster.token)
  tasks:
    - name: build-tekton-demo
      taskRef:
        name: build-docker-image-from-git-source
      resources:
        inputs:
          - name: docker-source
            resource: source-repo
        outputs:
          - name: builtImage
            resource: web-image
      params:
      - name: environment
        value: $(params.environment)        
      - name: image-version
        value: $(params.image-version)


