apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: frontend-runner
spec:
  pipelineRef:
    name: frontend-pipeline
  podTemplate:
    securityContext:
      runAsNonRoot: true
      runAsUser: 1001
    volumes:
    - name: my-cache
      persistentVolumeClaim:
        claimName: my-volume-claim
