apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: front-end-pipeline-run
spec:
  serviceAccountName: tekton-service-account
  pipelineRef:
    name: front-end-pipeline
  params:
  - name: image
    value: reabaln/front-end
  - name: tag
    value: "0.1"
  workspaces:
  - name: shared-workspace
    persistentvolumeclaim:
      claimName: front-end-source-pvc
