apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: pipeline-run-local-1
spec:
  serviceAccountName: tekton-service-account
  pipelineRef:
    name: tekton-pipeline
  resources:
    - name: source-repo
      resourceRef:
        name: training-tekton-git
    - name: web-image
      resourceRef:
        name: training-tekton-image
  params:
    - name: image-version
      value: "0-dev"
    - name: environment
      value: "dev"
