apiVersion: tekton.dev/v1alpha1
kind: PipelineResource
metadata:
  name: training-tekton-git
spec:
  type: git
  params:
    - name: revision
      value: master
    - name: url
      value: https://github.com/Reabaln/capstone-project/
---
apiVersion: tekton.dev/v1alpha1
kind: PipelineResource
metadata:
  name: training-tekton-image
spec:
  type: image
  params:
    - name: url
      value: reabaln/front-end
