apiVersion: v1
kind: Secret
metadata:
  name: reab-docker-hub-creds
  annotations:
    tekton.dev/docker-0: https://index.docker.io/v1/ # Described below
type: kubernetes.io/basic-auth
stringData:
  username: reabaln  
  password: d7ce4bc6-027f-4a26-8305-bd0aa4eb5c3f
