apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: build-docker-image-from-git-source
spec:
  params:
    - default: $(resources.inputs.docker-source.path)/src/Dockerfile
      description: The path to the dockerfile to build
      name: pathToDockerFile
      type: string
    - default: $(resources.inputs.docker-source.path)/src
      description: |
        The build context used by Kaniko
        (https://github.com/GoogleContainerTools/kaniko#kaniko-build-contexts)
      name: pathToContext
      type: string
    - name: image-version
      type: string
    - name: environment
      type: string
      description: dev/test/prod
  resources:
    inputs:
      - name: docker-source
        type: git
    outputs:
      - name: builtImage
        type: image
  steps:
    - image: busybox
      name: show-dockerfile
      resources: {}
      script: cat $(params.pathToDockerFile)
    - image: busybox
      name: docker-image
      resources: {}
      script: echo $(resources.outputs.builtImage.url):$(params.image-version)
    - args:
        - '--dockerfile=$(params.pathToDockerFile)'
        - '--destination=$(resources.outputs.builtImage.url):$(params.image-version)'
        - '--context=$(params.pathToContext)'
      command:
        - /kaniko/executor
      env:
        - name: DOCKER_CONFIG
          value: /tekton/home/.docker/
      image: 'gcr.io/kaniko-project/executor:v0.17.1'
      name: build-and-push
      resources: {}
      securityContext:
        runAsUser: 0
