apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: orders-pipeline-run
spec:
  serviceAccountName: tekton-service-account
  pipelineRef:
    name: orders-pipeline
  params:
  - name: image
    value: reabaln/orders
  - name: tag
    value: "0.1"
  workspaces:
  - name: shared-workspace
    persistentvolumeclaim:
      claimName: orders-source-pvc
