apiVersion: apps/v1
kind: Deployment
metadata:
  name: front-end
  namespace: test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: front-end
  template:
    metadata:
      labels:
        app: front-end
    spec:
      containers:
      - name: front-end
        image: reabaln/front-end:1.0
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
        ports:
        - containerPort: 8079

---
apiVersion: v1
kind: Service
metadata:
  name: front-end
  labels:
    name: front-end
  namespace: test 
spec:
  selector:
    app: front-end
  ports:
  - port: 8079 

