apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: front-end-pipeline-run
spec:
  serviceAccountName: tekton-service-account
  pipelineRef:
    name: front-end-pipeline
  params:
  - name: image
    value: reabaln/front-end
  - name: tag
    value: "0.1"
  - name: test-image
    value: reabaln/e2e-test
  - name: test-tag
    value: "0.3"
  - name: service
    value: front-end
  workspaces:
  - name: shared-workspace
    persistentvolumeclaim:
      claimName: front-end-source-pvc
