apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: catalogue-pipeline-run
spec:
  serviceAccountName: tekton-service-account
  pipelineRef:
    name: catalogue-pipeline
  params:
  - name: image
    value: reabaln/catalogue:0.1
  workspaces:
  - name: shared-workspace
    persistentvolumeclaim:
      claimName: kaniko-source-pvc
