apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: e2e-test-pipeline
spec:
  params:
  - name: image
    description: reference of the image to build
  - name: tag
    description: Tag of the images to build
  tasks:
  - name: run-test
    taskRef:	
      name: e2e-test
    params:	
      - name: path	
        value: /e2e-test/runner.sh  #configure: may change according to your source
      - name: imageUrl
        value: $(params.image) 
      - name: imageTag
        value: $(params.tag)
