apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: e2e-test-pipeline
spec:
  workspaces:
  - name: shared-workspace
  params:
  - name: image
    description: reference of the image to build
  - name: tag
    description: Tag of the images to build
  tasks:
  - name: fetch-repository	
    taskRef:	
      name: git-clone	
    workspaces:	
    - name: output	
      workspace: shared-workspace	
    params:	
    - name: url	
      value: https://github.com//Reabaln/capstone-project	
    - name: subdirectory	
      value: ""	
    - name: deleteExisting	
      value: "true"
  - name: run-test
    taskRef:	
      name: e2e-test
    workspaces:
    - name: source
      workspace: shared-workspace
    params:	
      - name: path	
        value: e2e-js-test/runner.sh #configure: may change according to your source
      - name: imageUrl
        value: $(params.image) 
      - name: imageTag
        value: $(params.tag)
