apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: kaniko-test-pipeline-run
spec:
  serviceAccountName: tekton-service-account
  pipelineRef:
    name: kaniko-test-pipeline
  params:
  - name: image
    value: reabaln/front-end:0.3
  workspaces:
  - name: shared-workspace
    persistentvolumeclaim:
      claimName: kaniko-source-pvc
