apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: to-prod
spec:
  workspaces:
  - name: shared-workspace
  tasks:
  - name: fetch-repository
    taskRef:
      name: git-clone
    workspaces:
    - name: output
      workspace: shared-workspace
    params:
    - name: url
      value: https://github.com//Reabaln/capstone-project
    - name: subdirectory
      value: ""
    - name: deleteExisting
      value: "true"
  - name: deploy-web	
    runAfter:
    - fetch-repository
    taskRef:	
      name: deploy-using-kubectl
    workspaces:
    - name: source
      workspace: shared-workspace
    params:	
      - name: path	
        value: ./deploy/k8s/sockshop-app.yaml #configure: may change according to your source	
